update build-release to accept the version instead of hardcoding it [#276]

diff --git a/scripts/build-release b/scripts/build-release
--- a/scripts/build-release
+++ b/scripts/build-release
@@ -1,9 +1,8 @@
 #!/usr/bin/env bash
 
 COLOR_RED='\033[0;31m'
-os=$(uname)
+COLOR_NONE='\033[0m'
 PROVIDER="heroku"
-VERSION=$(go run ${PROVIDER}/version.go)
 CURRENT_GIT_BRANCH=$(git rev-parse --abbrev-ref HEAD)
 
 if [ $CURRENT_GIT_BRANCH != 'master' ]; then
@@ -14,6 +13,18 @@ if [ $CURRENT_GIT_BRANCH != 'master' ]; then
   exit 1
 fi
 
+if [ $# -ne 1 ]; then
+  printf "\n"
+  printf "${COLOR_RED} Error: Release version argument required. \n\n ${COLOR_NONE}"
+  printf " Example: \n\n    ./scripts/build 0.9.0 \n\n"
+  printf "  Example (make): \n\n    make release version=0.9.0 \n"
+  printf "\n"
+
+  exit 1
+fi
+
+VERSION="v${1}"
+
 echo "Pulling down latest from origin"
 git pull origin master
 
@@ -22,19 +33,28 @@ git checkout master
 
 echo "Checking if master branch is clean"
 if [ "$(git status --porcelain)" != "" ]; then
-  echo "branch is not clean. please add/commit or stage any changes first"
+  printf "\n"
+  printf "${COLOR_RED} Error: branch is not clean. please add/commit or stage any changes first"
+  printf "\n"
+
   exit 1
 fi
 
 echo "Checking if local & remote master branch are in sync"
 if [ "$(git diff master origin/master)" != "" ]; then
-  echo "Local and remote master branch are not in sync. Please rectify"
+  printf "\n"
+  printf "${COLOR_RED} Local and remote master branch are not in sync"
+  printf "\n"
+
   exit 1
 fi
 
-echo "Checking if the tag already exists"
-if git show ${VERSION} >> /dev/null 2>&1 || false ; then
-  echo "tag ${VERSION} already exists. Did you forget to bump the version in version/version.go file?"
+echo "Checking if ${VERSION} tag already exists"
+if git rev-parse "$VERSION" >/dev/null 2>&1; then
+  printf "\n"
+  printf "${COLOR_RED} Error: ${VERSION} already exists! ${COLOR_NONE}"
+  printf "\n"
+
   exit 1
 fi
 
